### PR TITLE
Updated all the submodules to latest versions as of 18.02.15

### PR DESCRIPTION
**Pull request by voobscout**
as requested, a PR for issue #225

### CODE REVIEW

**Comment by senny** [comment]
@voobscout awesome!! :yellow_heart: 

@jone @tonini can you guys give this a spin and see how it turns out? Please report back when you feel comfortable with the pinning or when there are issues.

**Comment by senny** [comment]
@voobscout after upgrading I can't boot up Emacs anymore. Error is:

```
File error: Cannot open load file, no such file or directory, git-commit-mode
```

Probably related to new dependencies introduced by one of the modes. Cabbage is supposed to work out of the box so we either make it optional or bundle it as well.

**Comment by voobscout** [comment]
I'm not a lisper by any means, for me it seems to work and i can see git-commit-mode as installed package... Perhaps the newer magit from melpa installed it as dependancy?

**Comment by senny** [comment]
yes that might very well be the case. Have a look at the output of `list-packages`. Maybe you can figure out wether it's been installed somewhere into your Emacs configurations.

**Comment by voobscout** [comment]
git-commit-mode is an installed package.

Status: Installed in `~/.emacs.d/elpa/git-commit-mode-20141014.1634/' (unsigned).
Archive: n/a
Version: 20141014.1634
Summary: Major mode for editing git commit messages
Homepage: https://github.com/magit/git-modes
Keywords: convenience vc git

**Comment by senny** [comment]
@voobscout I tried to get all these versions running but gave up after an hour of tracking down errors. Many of the updated packages have unresolved dependencies or configuration changes. It's very hard to update everything in one go. Instead I did focus on `magit` and `master` now ships with an up-to-date magit version including `git-modes`.

Thank you for reporting :yellow_heart: . If you have troubles with other out-of-date packages, please file an issue.

**Pull request closed without merging**
